app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /  

app_usuario:
    resource: "@AppBundle/Resources/config/routing/usuario.yml"
    prefix: /usuario    

app_tarea:
    resource: "@AppBundle/Resources/config/routing/tarea.yml"
    prefix: /tarea